plugin:
    name:        'zaxbux.gmaildriver::lang.plugin.name'
    description: 'zaxbux.gmaildriver::lang.plugin.description'
    author:      'Zachary Schneider'
    icon:        'icon-envelope-square'
    homepage:    'https://github.com/zaxbux/wn-gmaildriver-plugin/'